
runtime: python39
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75

handlers:
  - url: /.*
    script: auto

env_variables:
  PORT: 8080

entrypoint: streamlit run tdf-bart.py --server.port $PORT