apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app-container
        image: gcr.io/vcc-deployment/streamlit-app:latest  # Update with your GCR image
        ports:
        - containerPort: 8501

