apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: streamlit-app-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: streamlit-app-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 85
