name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  # First job: Download model and prepare environment
  prepare-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pre-download BART model
      run: |
        python -c "from transformers import BartTokenizer, BartForConditionalGeneration; BartTokenizer.from_pretrained('facebook/bart-large-cnn'); BartForConditionalGeneration.from_pretrained('facebook/bart-large-cnn');"
      # Preload the model before deployment to speed up the app start

    - name: Save cache for model and dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/huggingface
          ~/.local/lib/python3.9/site-packages
        key: ${{ runner.os }}-huggingface-models-${{ hashFiles('requirements.txt') }}

  # Second job: Deploy to Google App Engine (depends on the first job)
  deploy-gcp:
    runs-on: ubuntu-latest
    needs: prepare-environment  # Ensures that this job runs after the environment preparation

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2.1.3
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        export_default_credentials: true

    - name: Showing the files present (for debugging)
      run: ls -la

    - name: Deploy to Google App Engine
      run: gcloud app deploy --quiet
