name: Deploy to Google App Engine

on:
  push:
    paths:
      - 'tdf-bart.py'
      - 'gae_deploy.yaml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Google Cloud credentials
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > /tmp/credentials.json

    - name: Authenticate with Google Cloud
      run: |
        gcloud auth activate-service-account --key-file=/tmp/credentials.json
        gcloud config set project ${{ secrets.GOOGLE_PROJECT_ID }}

    - name: Deploy to Google App Engine
      run: |
        gcloud app deploy --quiet
