name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

  install-dependencies:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0.7.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.7.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Google App Engine
      run: |
        gcloud app deploy --quiet
