name: GKE Deploy on Push to Main

# Trigger the action on pushes to the main branch
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: vcc-deployment
  PROJECT_NUMBER: 727416581731

  CLUSTER: streamlit-cluster
  CLUSTER_ZONE: asia-south2-b

  REPOSITORY: gcr.io
  REPOSITORY_REGION: us

  IMAGE: streamlit-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    #
    # Authenticate to Google Cloud using workload identity federation
    #
    - id: 'auth'
      name: 'Obtain access token by using workload identity federation'
      uses: 'google-github-actions/auth@v0'
      with:
        create_credentials_file: true
        token_format: access_token
        workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
        service_account: github-actions-workflow@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

    - name: Connect to Artifact Registry
      run: |-
        echo ${{ steps.auth.outputs.access_token }} | docker login -u oauth2accesstoken --password-stdin https://${{ env.REPOSITORY_REGION }}-docker.pkg.dev

    - name: Connect to GKE
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.CLUSTER }}
        location: ${{ env.CLUSTER_ZONE }}

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/streamlit-app:latest .

    # Push Docker image to Google Container Registry
    - name: Push Docker image
      run: |
        docker push gcr.io/${{ env.PROJECT_ID }}/streamlit-app:latest

    # Install kubectl
    - name: Install kubectl
      run: |
        sudo apt-get update && sudo apt-get install -y kubectl

    # Get GKE credentials
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials streamlit-cluster --zone asia-south2-b --project ${{ env.PROJECT_ID }}

    # Deploy to GKE
    - name: Deploy to GKE
      run: |
        kubectl apply -f gke-deployment/gke-deployment.yaml
        kubectl apply -f gke-deployment/service.yaml
