name: GKE Deploy on Push to Main

# Trigger the action on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_GKE_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    # Authenticate Docker to Google Container Registry using gcloud
    - name: Configure Docker to use gcloud credentials
      run: |
        gcloud auth configure-docker gcr.io --quiet

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/streamlit-app:latest .

    # Push Docker image to Google Container Registry
    - name: Push Docker image
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/streamlit-app:latest

    # Install kubectl
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Get GKE credentials
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials streamlit-cluster --zone asia-south2-b --project ${{ secrets.GCP_PROJECT_ID }}

    # Deploy to GKE
    - name: Deploy to GKE
      run: |
        kubectl apply -f gke-deployment/gke-deployment.yaml
        kubectl apply -f gke-deployment/service.yaml

    # Check deployment status
    - name: Check deployment status
      run: |
        kubectl rollout status deployment/your-deployment-name
